import pytest

from solution import sort_me


arr = [
    9892,
    "EFDEr",
    2150,
    "unsICGBAeO",
    "ytu",
    "XBqansOcB",
    "nltpmV",
    "b",
    "QTSbAxp",
    "QSkXllesuI",
    "sqd",
    "UqcGl",
    7954,
    "JznuHVHuxl",
    "FDFO",
    "PrJiVnUSserFD",
    "wzgGMKOl",
    "BP",
    "NbxxipWEXqPIo",
    6874,
    "LVO",
    "BoHZXYnYyC",
    "suHUSHU",
    "xaspoiEORdDK",
    "DpWiAgfLbxKtwy",
    "gaZrDoiN",
    5678,
    "FEpaqrUoPVd",
    "xfccoDT",
    7743,
    "PfzBqMnPwWpHHT",
    9867,
    2000,
    "efJad",
    4643,
    "knfaFPkfga",
    "cATbdUqtDeJPf",
    9736,
    "IJvMOWFSrxPpj",
    9987,
    "safz",
    "RNmJuVjYff",
    "iISQShRukx",
    "wHd",
    "QqbIIHmOjDoiYX",
    7083,
    "baIpJQbgcJyRY",
    8235,
    "ullSwbik",
    4204,
    "ZNNlHdn",
    6445,
    "jVxDZks",
    "xvkssbknG",
    "rOHiLDQFwUFggYg",
    "YePXAyarRG",
    4080,
    3414,
    4764,
    "ekffByeXGMkyFB",
    7119,
    "kyPPvrikf",
    5610,
]
ans = [
    2150,
    2000,
    4080,
    5610,
    9892,
    7743,
    4643,
    7083,
    7954,
    6874,
    4204,
    3414,
    4764,
    8235,
    6445,
    9736,
    9867,
    9987,
    5678,
    7119,
    "XBqansOcB",
    "ekffByeXGMkyFB",
    "BoHZXYnYyC",
    "PrJiVnUSserFD",
    "xvkssbknG",
    "YePXAyarRG",
    "QSkXllesuI",
    "xaspoiEORdDK",
    "gaZrDoiN",
    "unsICGBAeO",
    "FDFO",
    "LVO",
    "BP",
    "xfccoDT",
    "PfzBqMnPwWpHHT",
    "suHUSHU",
    "nltpmV",
    "QqbIIHmOjDoiYX",
    "baIpJQbgcJyRY",
    "knfaFPkfga",
    "b",
    "sqd",
    "FEpaqrUoPVd",
    "efJad",
    "wHd",
    "cATbdUqtDeJPf",
    "RNmJuVjYff",
    "kyPPvrikf",
    "rOHiLDQFwUFggYg",
    "IJvMOWFSrxPpj",
    "ullSwbik",
    "UqcGl",
    "JznuHVHuxl",
    "wzgGMKOl",
    "ZNNlHdn",
    "NbxxipWEXqPIo",
    "QTSbAxp",
    "EFDEr",
    "jVxDZks",
    "ytu",
    "iISQShRukx",
    "DpWiAgfLbxKtwy",
    "safz",
]

data = [
    (["acvd", "bcc"], ["bcc", "acvd"]),
    (["14", "13"], ["13", "14"]),
    (["asdf", 14, "13", "asdf"], ["13", 14, "asdf", "asdf"]),
    (["bsde", "asdf", 14, "13"], ["13", 14, "bsde", "asdf"]),
    (["asdf", 14, "13", "asdf"], ["13", 14, "asdf", "asdf"]),
    (arr, ans),
]


@pytest.mark.parametrize("arr, result", data)
def test_sort_me(arr, result):
    assert sort_me(arr) == result
