from solution import scrolling_text


test_strings = [
    "abc", "codewars", "Hello world!", "123456789",
    "The quick brown fox jumps over the lazy dog"
]

test_solutions = [
    ['ABC', 'BCA', 'CAB'],
    ['CODEWARS', 'ODEWARSC', 'DEWARSCO', 'EWARSCOD', 'WARSCODE', 'ARSCODEW',
     'RSCODEWA', 'SCODEWAR'],
    [
        'HELLO WORLD!', 'ELLO WORLD!H', 'LLO WORLD!HE', 'LO WORLD!HEL',
        'O WORLD!HELL', ' WORLD!HELLO', 'WORLD!HELLO ', 'ORLD!HELLO W',
        'RLD!HELLO WO', 'LD!HELLO WOR', 'D!HELLO WORL', '!HELLO WORLD'
    ],
    [
        '123456789', '234567891', '345678912', '456789123', '567891234',
        '678912345', '789123456', '891234567', '912345678'
    ],
    [
        'THE QUICK BROWN FOX JUMPS OVER THE LAZY DOG',
        'HE QUICK BROWN FOX JUMPS OVER THE LAZY DOGT',
        'E QUICK BROWN FOX JUMPS OVER THE LAZY DOGTH',
        ' QUICK BROWN FOX JUMPS OVER THE LAZY DOGTHE',
        'QUICK BROWN FOX JUMPS OVER THE LAZY DOGTHE ',
        'UICK BROWN FOX JUMPS OVER THE LAZY DOGTHE Q',
        'ICK BROWN FOX JUMPS OVER THE LAZY DOGTHE QU',
        'CK BROWN FOX JUMPS OVER THE LAZY DOGTHE QUI',
        'K BROWN FOX JUMPS OVER THE LAZY DOGTHE QUIC',
        ' BROWN FOX JUMPS OVER THE LAZY DOGTHE QUICK',
        'BROWN FOX JUMPS OVER THE LAZY DOGTHE QUICK ',
        'ROWN FOX JUMPS OVER THE LAZY DOGTHE QUICK B',
        'OWN FOX JUMPS OVER THE LAZY DOGTHE QUICK BR',
        'WN FOX JUMPS OVER THE LAZY DOGTHE QUICK BRO',
        'N FOX JUMPS OVER THE LAZY DOGTHE QUICK BROW',
        ' FOX JUMPS OVER THE LAZY DOGTHE QUICK BROWN',
        'FOX JUMPS OVER THE LAZY DOGTHE QUICK BROWN ',
        'OX JUMPS OVER THE LAZY DOGTHE QUICK BROWN F',
        'X JUMPS OVER THE LAZY DOGTHE QUICK BROWN FO',
        ' JUMPS OVER THE LAZY DOGTHE QUICK BROWN FOX',
        'JUMPS OVER THE LAZY DOGTHE QUICK BROWN FOX ',
        'UMPS OVER THE LAZY DOGTHE QUICK BROWN FOX J',
        'MPS OVER THE LAZY DOGTHE QUICK BROWN FOX JU',
        'PS OVER THE LAZY DOGTHE QUICK BROWN FOX JUM',
        'S OVER THE LAZY DOGTHE QUICK BROWN FOX JUMP',
        ' OVER THE LAZY DOGTHE QUICK BROWN FOX JUMPS',
        'OVER THE LAZY DOGTHE QUICK BROWN FOX JUMPS ',
        'VER THE LAZY DOGTHE QUICK BROWN FOX JUMPS O',
        'ER THE LAZY DOGTHE QUICK BROWN FOX JUMPS OV',
        'R THE LAZY DOGTHE QUICK BROWN FOX JUMPS OVE',
        ' THE LAZY DOGTHE QUICK BROWN FOX JUMPS OVER',
        'THE LAZY DOGTHE QUICK BROWN FOX JUMPS OVER ',
        'HE LAZY DOGTHE QUICK BROWN FOX JUMPS OVER T',
        'E LAZY DOGTHE QUICK BROWN FOX JUMPS OVER TH',
        ' LAZY DOGTHE QUICK BROWN FOX JUMPS OVER THE',
        'LAZY DOGTHE QUICK BROWN FOX JUMPS OVER THE ',
        'AZY DOGTHE QUICK BROWN FOX JUMPS OVER THE L',
        'ZY DOGTHE QUICK BROWN FOX JUMPS OVER THE LA',
        'Y DOGTHE QUICK BROWN FOX JUMPS OVER THE LAZ',
        ' DOGTHE QUICK BROWN FOX JUMPS OVER THE LAZY',
        'DOGTHE QUICK BROWN FOX JUMPS OVER THE LAZY ',
        'OGTHE QUICK BROWN FOX JUMPS OVER THE LAZY D',
        'GTHE QUICK BROWN FOX JUMPS OVER THE LAZY DO'
    ]
]


def test_scrolling_test():
    for text, expected in zip(test_strings, test_solutions):
        assert scrolling_text(text) == expected
